INSERT INTO MY_TABLE(year, constructor, points) VALUES (1958, 'Vanwall', 48.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1958, 'Ferrari', 40.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1958, 'Cooper', 31.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1958, 'BRM', 18.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1958, 'Maserati', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1958, 'Lotus', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1959, 'Cooper', 40.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1959, 'Ferrari', 32.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1959, 'BRM', 18.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1959, 'Lotus', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1960, 'Cooper', 48.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1960, 'Lotus', 34.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1960, 'Ferrari', 26.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1960, 'BRM', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1960, 'Cooper', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1960, 'Cooper', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1960, 'Porsche', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1961, 'Ferrari', 40.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1961, 'Lotus', 32.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1961, 'Porsche', 22.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1961, 'Cooper', 14.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1961, 'BRM', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1962, 'BRM', 42.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1962, 'Lotus', 36.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1962, 'Cooper', 29.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1962, 'Lola', 19.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1962, 'Porsche', 18.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1962, 'Ferrari', 18.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1962, 'Brabham', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1962, 'Lotus', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1963, 'Lotus', 54.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1963, 'BRM', 36.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1963, 'Brabham', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1963, 'Ferrari', 26.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1963, 'Cooper', 25.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1963, 'BRP', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1963, 'Porsche', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1963, 'Lotus', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1964, 'Ferrari', 45.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1964, 'BRM', 42.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1964, 'Lotus', 37.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1964, 'Brabham', 30.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1964, 'Cooper', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1964, 'Brabham', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1964, 'BRP', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1964, 'Lotus', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1965, 'Lotus', 54.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1965, 'BRM', 45.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1965, 'Brabham', 27.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1965, 'Ferrari', 26.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1965, 'Cooper', 14.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1965, 'Honda', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1965, 'Brabham', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1965, 'Lotus', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'Brabham', 42.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'Ferrari', 31.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'Cooper', 30.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'BRM', 22.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'Lotus', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'Lotus', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'Eagle', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'Honda', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'McLaren', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'Brabham', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'McLaren', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1966, 'Brabham', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'Brabham', 63.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'Lotus', 44.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'Cooper', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'Honda', 20.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'Ferrari', 20.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'BRM', 17.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'Eagle', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'Cooper', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'Lotus', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'McLaren', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1967, 'Brabham', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'Lotus', 62.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'McLaren', 49.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'Matra', 45.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'Ferrari', 32.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'BRM', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'Honda', 14.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'Cooper', 14.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'Brabham', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'Matra', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1968, 'McLaren', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1969, 'Matra', 66.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1969, 'Brabham', 49.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1969, 'Lotus', 47.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1969, 'McLaren', 38.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1969, 'Ferrari', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1969, 'BRM', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1970, 'Lotus', 59.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1970, 'Ferrari', 52.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1970, 'March', 48.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1970, 'Brabham', 35.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1970, 'McLaren', 35.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1970, 'BRM', 23.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1970, 'Matra', 23.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1970, 'Surtees', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1971, 'Tyrrell', 73.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1971, 'BRM', 36.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1971, 'Ferrari', 33.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1971, 'March', 33.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1971, 'Lotus', 21.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1971, 'McLaren', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1971, 'Matra', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1971, 'Surtees', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1971, 'Brabham', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1972, 'Lotus', 61.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1972, 'Tyrrell', 51.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1972, 'McLaren', 47.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1972, 'Ferrari', 33.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1972, 'Surtees', 18.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1972, 'March', 15.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1972, 'BRM', 14.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1972, 'Matra', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1972, 'Brabham', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'Lotus', 92.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'Tyrrell', 82.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'McLaren', 58.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'Brabham', 22.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'March', 14.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'Ferrari', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'BRM', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'Shadow', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'Surtees', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'Iso-Marlboro', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1973, 'Tecno', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'McLaren', 73.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'Ferrari', 65.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'Tyrrell', 52.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'Lotus', 42.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'Brabham', 35.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'Hesketh', 15.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'BRM', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'Shadow', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'March', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'Iso-Marlboro', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'Surtees', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1974, 'Lola', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Ferrari', 72.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Brabham', 54.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'McLaren', 53.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Hesketh', 33.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Tyrrell', 25.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Shadow', 9.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Lotus', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'March', 7.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Frank Williams Racing Cars', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Parnelli', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Hill', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Penske', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1975, 'Ensign', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Ferrari', 83.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'McLaren', 74.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Tyrrell', 71.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Lotus', 29.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Penske', 20.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Ligier', 20.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'March', 19.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Shadow', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Brabham', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Surtees', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Fittipaldi', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Ensign', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1976, 'Parnelli', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Ferrari', 95.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Lotus', 62.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'McLaren', 60.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Wolf', 55.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Brabham', 27.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Tyrrell', 27.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Shadow', 23.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Ligier', 18.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Fittipaldi', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Ensign', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Surtees', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1977, 'Penske', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Lotus', 86.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Ferrari', 58.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Brabham', 53.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Tyrrell', 38.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Wolf', 24.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Ligier', 19.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Fittipaldi', 17.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'McLaren', 15.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Williams', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Arrows', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Shadow', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Renault', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Surtees', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1978, 'Ensign', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Ferrari', 113.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Williams', 75.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Ligier', 61.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Lotus', 39.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Tyrrell', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Renault', 26.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'McLaren', 15.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Brabham', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Arrows', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Shadow', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'ATS', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1979, 'Fittipaldi', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Williams', 120.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Ligier', 66.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Brabham', 55.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Renault', 38.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Lotus', 14.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Tyrrell', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Arrows', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Fittipaldi', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'McLaren', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Ferrari', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1980, 'Alfa Romeo', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Williams', 95.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Brabham', 61.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Renault', 54.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Ligier', 44.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Ferrari', 34.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'McLaren', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Lotus', 22.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Arrows', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Alfa Romeo', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Tyrrell', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Ensign', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'Theodore', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1981, 'ATS', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Ferrari', 74.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'McLaren', 69.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Renault', 62.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Williams', 58.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Lotus', 30.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Tyrrell', 25.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Brabham', 22.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Ligier', 20.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Brabham', 19.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Alfa Romeo', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Arrows', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'ATS', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Osella', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1982, 'Fittipaldi', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Ferrari', 89.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Renault', 79.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Brabham', 72.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Williams', 36.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'McLaren', 34.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Alfa Romeo', 18.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Tyrrell', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Lotus', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Toleman', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Arrows', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Williams', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Theodore', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1983, 'Lotus', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'McLaren', 143.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Ferrari', 57.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Lotus', 47.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Brabham', 38.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Renault', 34.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Williams', 25.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Toleman', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Alfa Romeo', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Ligier', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Arrows', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Arrows', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Osella', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1984, 'Tyrrell', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'McLaren', 90.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'Ferrari', 82.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'Williams', 71.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'Lotus', 71.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'Brabham', 26.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'Ligier', 23.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'Renault', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'Arrows', 14.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'Tyrrell', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1985, 'Tyrrell', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'Williams', 141.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'McLaren', 96.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'Lotus', 58.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'Ferrari', 37.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'Ligier', 29.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'Benetton', 19.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'Tyrrell', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'Lola', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'Brabham', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1986, 'Arrows', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Williams', 137.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'McLaren', 76.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Lotus', 64.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Ferrari', 53.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Benetton', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Tyrrell', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Arrows', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Brabham', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Lola', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Zakspeed', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'Ligier', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'March', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1987, 'AGS', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'McLaren', 199.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'Ferrari', 65.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'Benetton', 39.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'Lotus', 23.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'Arrows', 23.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'March', 22.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'Williams', 20.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'Tyrrell', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'Rial', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1988, 'Minardi', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'McLaren', 141.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Williams', 77.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Ferrari', 59.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Benetton', 39.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Tyrrell', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Lotus', 15.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Arrows', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Dallara', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Brabham', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Onyx', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Minardi', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'March', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Rial', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Ligier', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'AGS', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1989, 'Lola', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'McLaren', 121.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'Ferrari', 110.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'Benetton', 71.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'Williams', 57.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'Tyrrell', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'Lola', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'Leyton House', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'Lotus', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'Brabham', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1990, 'Arrows', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'McLaren', 139.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Williams', 125.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Ferrari', 55.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Benetton', 38.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Jordan', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Tyrrell', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Minardi', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Dallara', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Lotus', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Brabham', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Lola', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1991, 'Leyton House', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Williams', 164.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'McLaren', 99.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Benetton', 91.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Ferrari', 21.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Lotus', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Tyrrell', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Footwork', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Ligier', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'March', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Dallara', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Venturi', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Minardi', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1992, 'Jordan', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Williams', 168.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'McLaren', 84.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Benetton', 72.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Ferrari', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Ligier', 23.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Lotus', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Sauber', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Minardi', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Footwork', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Larrousse', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1993, 'Jordan', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Williams', 118.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Benetton', 103.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Ferrari', 71.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'McLaren', 42.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Jordan', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Ligier', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Tyrrell', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Sauber', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Footwork', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Minardi', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1994, 'Larrousse', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'Benetton', 137.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'Williams', 112.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'Ferrari', 73.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'McLaren', 30.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'Ligier', 24.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'Jordan', 21.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'Sauber', 18.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'Footwork', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'Tyrrell', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1995, 'Minardi', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1996, 'Williams', 175.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1996, 'Ferrari', 70.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1996, 'Benetton', 68.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1996, 'McLaren', 49.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1996, 'Jordan', 22.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1996, 'Ligier', 15.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1996, 'Sauber', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1996, 'Tyrrell', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1996, 'Footwork', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'Williams', 123.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'Ferrari', 102.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'Benetton', 67.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'McLaren', 63.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'Jordan', 33.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'Prost', 21.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'Sauber', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'Arrows', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'Stewart', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1997, 'Tyrrell', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1998, 'McLaren', 156.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1998, 'Ferrari', 133.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1998, 'Williams', 38.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1998, 'Jordan', 34.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1998, 'Benetton', 33.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1998, 'Sauber', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1998, 'Arrows', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1998, 'Stewart', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1998, 'Prost', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'Ferrari', 128.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'McLaren', 124.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'Jordan', 61.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'Stewart', 36.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'Williams', 35.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'Benetton', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'Prost', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'Sauber', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'Arrows', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (1999, 'Minardi', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'Ferrari', 170.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'McLaren', 152.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'Williams', 36.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'Benetton', 20.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'BAR', 20.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'Jordan', 17.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'Arrows', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'Sauber', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'Jaguar', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'Minardi', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2000, 'Prost', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'Ferrari', 179.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'McLaren', 102.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'Williams', 80.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'Sauber', 21.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'Jordan', 19.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'BAR', 17.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'Benetton', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'Jaguar', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'Prost', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'Arrows', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2001, 'Minardi', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'Ferrari', 221.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'Williams', 92.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'McLaren', 65.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'Renault', 23.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'Sauber', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'Jordan', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'Jaguar', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'BAR', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'Minardi', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'Toyota', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2002, 'Arrows', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'Ferrari', 158.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'Williams', 144.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'McLaren', 142.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'Renault', 88.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'BAR', 26.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'Sauber', 19.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'Jaguar', 18.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'Toyota', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'Jordan', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2003, 'Minardi', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'Ferrari', 262.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'BAR', 119.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'Renault', 105.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'Williams', 88.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'McLaren', 69.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'Sauber', 34.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'Jaguar', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'Toyota', 9.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'Jordan', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2004, 'Minardi', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'Renault', 191.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'McLaren', 182.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'Ferrari', 100.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'Toyota', 88.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'Williams', 66.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'BAR', 38.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'Red Bull', 34.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'Sauber', 20.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'Jordan', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2005, 'Minardi', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'Renault', 206.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'Ferrari', 201.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'McLaren', 110.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'Honda', 86.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'BMW Sauber', 36.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'Toyota', 35.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'Red Bull', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'Williams', 11.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'Toro Rosso', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'Midland', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2006, 'Super Aguri', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'Ferrari', 204.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'BMW Sauber', 101.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'Renault', 51.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'Williams', 33.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'Red Bull', 24.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'Toyota', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'Toro Rosso', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'Honda', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'Super Aguri', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'Spyker', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2007, 'McLaren', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'Ferrari', 172.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'McLaren', 151.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'BMW Sauber', 135.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'Renault', 80.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'Toyota', 56.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'Toro Rosso', 39.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'Red Bull', 29.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'Williams', 26.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'Honda', 14.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'Force India', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2008, 'Super Aguri', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'Brawn', 172.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'Red Bull', 153.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'McLaren', 71.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'Ferrari', 70.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'Toyota', 59.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'BMW Sauber', 36.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'Williams', 34.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'Renault', 26.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'Force India', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2009, 'Toro Rosso', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Red Bull', 498.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'McLaren', 454.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Ferrari', 396.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Mercedes', 214.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Renault', 163.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Williams', 69.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Force India', 68.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Sauber', 44.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Toro Rosso', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Lotus Racing', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'HRT', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2010, 'Virgin', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Red Bull', 650.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'McLaren', 497.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Ferrari', 375.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Mercedes', 165.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Renault', 73.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Force India', 69.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Sauber', 44.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Toro Rosso', 41.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Williams', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Lotus Racing', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'HRT', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2011, 'Virgin', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Red Bull', 460.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Ferrari', 400.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'McLaren', 378.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Lotus', 303.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Mercedes', 142.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Sauber', 126.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Force India', 109.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Williams', 76.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Toro Rosso', 26.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Caterham', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'Marussia', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2012, 'HRT', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Red Bull', 596.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Mercedes', 360.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Ferrari', 354.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Lotus', 315.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'McLaren', 122.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Force India', 77.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Sauber', 57.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Toro Rosso', 33.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Williams', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Marussia', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2013, 'Caterham', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Mercedes', 701.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Red Bull', 405.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Williams', 320.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Ferrari', 216.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'McLaren', 181.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Force India', 155.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Toro Rosso', 30.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Lotus', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Marussia', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Sauber', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2014, 'Caterham', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'Mercedes', 703.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'Ferrari', 428.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'Williams', 257.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'Red Bull', 187.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'Force India', 136.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'Lotus', 78.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'Toro Rosso', 67.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'Sauber', 36.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'McLaren', 27.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2015, 'Marussia', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Mercedes', 765.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Red Bull', 468.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Ferrari', 398.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Force India', 173.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Williams', 138.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'McLaren', 76.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Toro Rosso', 63.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Haas', 29.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Renault', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Sauber', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2016, 'Manor', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'Mercedes', 668.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'Ferrari', 522.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'Red Bull', 368.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'Force India', 187.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'Williams', 83.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'Renault', 57.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'Toro Rosso', 53.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'Haas', 47.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'McLaren', 30.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2017, 'Sauber', 5.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Mercedes', 655.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Ferrari', 571.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Red Bull', 419.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Renault', 122.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Haas', 93.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'McLaren', 62.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Force India', 52.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Sauber', 48.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Toro Rosso', 33.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Williams', 7.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2018, 'Force India', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'Mercedes', 739.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'Ferrari', 504.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'Red Bull', 417.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'McLaren', 145.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'Renault', 91.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'Toro Rosso', 85.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'Racing Point', 73.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'Alfa Romeo', 57.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'Haas', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2019, 'Williams', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'Mercedes', 573.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'Red Bull', 319.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'McLaren', 202.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'Racing Point', 195.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'Renault', 181.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'Ferrari', 131.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'AlphaTauri', 107.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'Alfa Romeo', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'Haas', 3.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2020, 'Williams', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'Mercedes', 613.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'Red Bull', 585.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'Ferrari', 323.50);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'McLaren', 275.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'Alpine', 155.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'AlphaTauri', 142.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'Aston Martin', 77.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'Williams', 23.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'Alfa Romeo', 13.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2021, 'Haas', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'Red Bull', 759.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'Ferrari', 554.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'Mercedes', 515.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'Alpine', 173.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'McLaren', 159.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'Alfa Romeo', 55.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'Aston Martin', 55.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'Haas', 37.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'AlphaTauri', 35.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2022, 'Williams', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'Red Bull', 860.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'Mercedes', 409.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'Ferrari', 406.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'McLaren', 302.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'Aston Martin', 280.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'Alpine', 120.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'Williams', 28.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'AlphaTauri', 25.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'Alfa Romeo', 16.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2023, 'Haas', 12.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'McLaren', 666.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'Ferrari', 652.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'Red Bull', 589.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'Mercedes', 468.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'Aston Martin', 94.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'Alpine', 65.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'Haas', 58.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'RB', 46.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'Williams', 17.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2024, 'Kick Sauber', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'McLaren', 833.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'Mercedes', 469.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'Red Bull', 451.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'Ferrari', 398.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'Williams', 137.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'Racing Bulls', 92.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'Aston Martin', 89.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'Haas', 79.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'Kick Sauber', 70.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2025, 'Alpine', 22.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Mercedes', 43.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Ferrari', 27.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'McLaren', 10.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Red Bull', 8.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Haas', 6.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Racing Bulls', 4.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Audi', 2.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Alpine', 1.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Williams', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Cadillac', 0.00);
INSERT INTO MY_TABLE(year, constructor, points) VALUES (2026, 'Aston Martin', 0.00);
